version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
  app:
    build: ./php
    image: php:7.4-fpm
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports: ["8889:80"]
        depends_on: ["db"]
  db:
    # build: ./mysql
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: ph2_webapp
      MYSQL_ROOT_USER: root
      # rootにすると入れる
      MYSQL_PASSWORD: "pass"
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "13306:3306"
    volumes:
      - ./initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/conf.d/my.cnf/my.conf
    stdin_open: true