version: "3"
volumes:
  db-volume:
  maildir: {}


services:
  db:
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
  app:
    build:
      context: ./app
    volumes:
      - ../src:/work/backend
      - ./app/usr/local/etc/php:/usr/local/etc/php
    depends_on: ["db"]
  web:
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../src:/work/backend
    depends_on: ["app"]

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp  